server.port: 9001

spring.data.mongodb:
  host: localhost
  port: 27017
  database: product-db

logging:
  level:
    root: INFO
    com.neta: DEBUG
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG